### ISSUE TITLE
Azure Blob requests showing as failure in AI

### ISSUE THREAD

**Issue by isaacabraham** [Microsoft/ApplicationInsights-dotnet-server#65] opened 2016-03-30 18:49 UTC
I'm not entirely sure what I think that the solution should be for this one.

There are API calls in the .NET Azure SDK that (I believe) convert e.g. HTTP 404s to true / false e.g. ```blob.Exists()```. The problem is that our code calls these API calls in many places and we're ending up with lots of false failures showing in AI simply because the dependency tracking module sees this as a 404 ergo it must be a failure.

We could add a filter for this but I think that you're going to find many other people in this (or similar) situation.

**Comment by abaranch** [comment] 2016-03-30 20:59
Thank you for reporting the issue.
You are right that for now workaround for that would be to create a [filter](https://azure.microsoft.com/en-us/blog/request-filtering-in-application-insights-with-telemetry-processor/)
We will think if we can do anything smart in the module to detect these cases. Right now module does not distinguish azure/notazure cases. It is just an http dependency with certain response code.

**Comment by AlexBulankou** [comment] 2016-03-31 01:01
Wouldn't this behavior be by design from dependency monitoring perspective? We are not saying that it is a an actionable failure, all we are saying is that dependency calls made by your application resulted in failure HTTP codes returned. It may be possible that these HTTP calls were made by libraries that treat them as non-error scenario, that is why the parent request won't fail. 

I am suggesting we should not attempt to introduce any additional heuristics to determine if 404 is actually expected and leave it up to the customer to override default successful/non-successful result.

**Comment by isaacabraham** [comment] 2016-03-31 07:06
Hey guys. Thanks for replying. So: -

1. This isn't just about Azure; it could happen in any API.

2. Many APIs use 404 not to indicate a failure but simple that a given resource does not exist.

I don't know what the solution is - maybe filter is the right way to do it - I just wanted to raise it as a situation where AI didn't do the "expected" thing that I would want in terms of behavior.

**Comment by AlexBulankou** [comment] 2016-03-31 16:34
Thanks - noted! Successful flag is clearly context-specific, we tried to pick the reasonable default HttpCode>=400, we'll consider how to make it easier to override this default for specific dependencies.

**Comment by isaacabraham** [comment] 2016-03-31 17:13
Cheers. I get the feeling (and there's no way to confirm this) that "web sites" style resources are normally 404 = failure whereas for back-end restful APIs and the like, 404 is more a semantic way of saying "doesn't exist".

**Comment by AlexBulankou** [comment] 2016-04-04 23:13
Closing this commend - we are planning to support this filtering on the UI side

**Closed by AlexBulankou** 2016-04-04 23:13 UTC
Labels: enhancement
