### ISSUE TITLE
DependencyTelemetry ends up as parent of _all_ RequestTelemetries in a selfhosted AspNet Core application.

### ISSUE THREAD

**Issue by cadwal** [Microsoft/ApplicationInsights-dotnet-server#1128] opened 2018-12-15 21:35 UTC
(This is on Net Fwk 4.7.2, AI 2.8.1)

I have come across some very odd behavior where a DependencyTelemetry (SQL call) becomes the the parent of all RequestTelemetries in in a selfhosted AspNet Core application. SQL calls actually happening during a request is nicely parented by that request itself.

This SQL call actually happens before AI is configured and initialized using AddApplicationInsightsTelemetry in ConfigureServices (but at that time CurrentActivity is null). (Checked using SQL Profiler). That is confusing in itself since I would assume that that Dependency should have been lost.

A bit of debugging tells me that the parenting is because an Activity for the dependency is active when any Request is served so that it becomes the Requests Activity:s parent. (Looking at CurrentActivity while the Controller is executing). 

The "root" Activity name has the spelling error fixed in commit 47dfb0c.

So I wonder where the activity.Stop() command corresponding to the Start in this line
https://github.com/Microsoft/ApplicationInsights-dotnet-server/blob/7aa78abcce42fa6108318f2b1e76feccb986af65/Src/DependencyCollector/Shared/Implementation/ClientServerDependencyTracker.cs#L80

is located? 

That Stop call never seems to happen in my case, and the Start call seems to happen far later that the actual SQL call happened, timing seems to be matched to slightly after the call to AddApplicationInsightsTelemetry.

**Comment by lmolkova** [comment] 2018-12-28 19:14
this is duplicate of https://github.com/Microsoft/ApplicationInsights-dotnet-server/issues/1090. Please try 2.9.0-beta2 and let us know if the issue is fixed.

**Closed by lmolkova** 2018-12-28 19:14 UTC

**Comment by cadwal** [comment] 2019-01-02 15:53
As far as I can tell right now, that fixes the issue.

(for some reason I have yet to find, request telemetry is no longer being sent in my application... no code changes or anything, but I could still see the difference with the inner SQL dependencies no longer being parented to the one happening prior to any request in 2.9.0-beta2)
