### ISSUE TITLE
On .NET 4.5.2 successful HTTP dependencies are logged as failing

### ISSUE THREAD

**Issue by AlexBulankou** [Microsoft/ApplicationInsights-dotnet-server#67] opened 2016-04-07 19:10 UTC
Try this example:
```
 static void Main(string[] args)
        {
            new DependencyTrackingTelemetryModule().Initialize(TelemetryConfiguration.Active);
            Test().Wait();
        }

        static async Task Test()
        {
            var result = await new HttpClient().GetAsync("https://www.bing.com/search?q=httpclient");
            var response = await WebRequest.Create("https://www.bing.com/search?q=webrequest").GetResponseAsync();                 
        }
```

These are dependencies that are getting logged on .NET 4.5.2. Note that we get nothing logged on 4.5 and 4.5.1 (probably expected) and on 4.6 everything is logged as expected

```
{"name":"Microsoft.ApplicationInsights.RemoteDependency","time":"2016-04-07T19:0
3:47.1438164Z","tags":{"ai.internal.sdkVersion":"rddf: 2.0.0.25000"},"data":{"ba
seType":"RemoteDependencyData","baseData":{"ver":2,"name":"https://www.bing.com/
search?q=httpclient","id":"R1YUAcsnqk8=","value":167.5677,"dependencyKind":1,"su
ccess":false}}}

{"name":"Microsoft.ApplicationInsights.RemoteDependency","time":"2016-04-07T19:0
3:47.7255489Z","tags":{"ai.internal.sdkVersion":"rddf: 2.0.0.25000"},"data":{"ba
seType":"RemoteDependencyData","baseData":{"ver":2,"name":"https://www.bing.com/
search?q=webrequest","id":"uGxqsnv1HTU=","value":487.8151,"dependencyKind":1,"su
ccess":false}}}
```

**Comment by AlexBulankou** [comment] 2016-04-07 19:17
From the customer report, looks like this is a regression from 1.2.3

**Comment by AlexBulankou** [comment] 2016-04-07 20:48
Verified that with 1.2.3 we are not reporting success flag at all:

```
{"name":"Microsoft.ApplicationInsights.RemoteDependency","time":"2016-04-07T20:4
3:33.3314554+00:00","tags":{"ai.internal.sdkVersion":"1.2.3.490"},"data":{"baseT
ype":"RemoteDependencyData","baseData":{"ver":2,"name":"https://www.bing.com/sea
rch?q=httpclient","kind":1,"value":170.2793,"dependencyKind":1,"async":true,"dep
endencySource":0}}}

{"name":"Microsoft.ApplicationInsights.RemoteDependency","time":"2016-04-07T20:4
3:34.0527809+00:00","tags":{"ai.internal.sdkVersion":"1.2.3.490"},"data":{"baseT
ype":"RemoteDependencyData","baseData":{"ver":2,"name":"https://www.bing.com/sea
rch?q=webrequest","kind":1,"value":216.2655,"dependencyKind":1,"async":true,"dep
endencySource":0}}}
```

**Comment by hannesdecorte** [comment] 2016-04-07 21:02
It look like with 4.5.2 and 2.0.0 the async flag isn't logged either. But maybe that's normal? Maybe the problem is that the result is always false because the call is not seen as async?
I'm the customer who reported it by the way. :-)

**Comment by AlexBulankou** [comment] 2016-04-07 22:23
async not reported is by design - we are no longer reporting this because we couldn't correctly determine async in the first place, so this was reported incorrectly in most cases

**Comment by hannesdecorte** [comment] 2016-04-09 08:00
Hi,

could it be that in 1.2.3 (and .NET 4.5.2) it works without installing the Application Insights Agent/Status Monitor on the machine? And in 2.0.0 (and .NET 4.5.2) the Agent/Monitor is required?

I ask because I have it working in our Test Cloud Service instance with version 2.0.0 but with the Agent/Monitor installed. In our Beta Cloud Service instance with version 2.0.0 it doesn't work (no Agent/Monitor installed). If I deploy in Beta Cloud Service instance with version 1.2.3 (no Agent/Monitor installed) it works (or at least success is reported but does it means it works...)

**Comment by abaranch** [comment] 2016-04-09 17:49
Currently what I see is that without StatusMonitor for 4.5.2 (app and runtime, so no 4.6 on the box) we see
1. remote dependency success is incorrect (regression from 1.2.3)
2. remote dependency count is doubled. Same as in 1.2.3
In both cases installing StatusMonitor will resolve the issue.
First issue we can fix, second one is related to the framework implementation where we get notification from framework twice. Most likely we would not be able to fix in on our side and since it is working fine in 4.6 looks like they fixed in on their side. I will update this thread when I investigate more.

**Closed** 2016-04-12 21:58 UTC
Labels: bug
