### ISSUE TITLE
Current HttpContext is NULL for DependencyTelemetry

### ISSUE THREAD

**Issue by sanjaysingh** [Microsoft/ApplicationInsights-dotnet-server#729] opened 2017-11-06 18:25 UTC
I am trying to log custom http headers using a custom telemetry initializer. This initializer extracts header from HttpContext.Current and then adds it as custom dimensions. This is working fine with requests telemetry, however i see that HttpContext is not available for dependency telemetries.

How can I get access to current http context? If not then what is an alternative way to log http headers of the request context with each dependency telemetry?

Other details:

- ASP .Net Web API application built on .Net framework 4.5
- Deployed in Azure as a Web Role. Issue however is reproducible locally as well. I can put breakpoint in the
custom initializer to find that HttpContext.Current is coming as null for dependency telemetry.
- The call to dependency is an Http async call.

**Comment by MS-TimothyMothra** [comment] 2017-11-06 21:58
Hi @sanjaysingh,
I'm going to be investigating this. Can you answer some questions please:

What technologies and versions do your app use?
Are your dependency requests async?

- Or if you can share a simple test app that can reproduce this issue, that would be a great help.
Thank you

**Comment by sanjaysingh** [comment] 2017-11-07 16:50
Hi @MS-TimothyMothra,
I have updated the issue with all the relevant details.
Thank you

**Comment by MS-TimothyMothra** [comment] 2017-11-08 23:57
Hi @sanjaysingh,
Let me confirm I understand your issue...

> Your WebApi project receives a request (A).
> While handling request (A), you send an outgoing async request (B). 
> 

**Question**:

1. When your TelemetryInitializer handles the DependencyTelemetry for request (B), are you trying to include the headers from request (A) or the headers of request (B) ?

Request (B) can be handled by any thread therefore we can't guarantee access to request (A)'s HttpContext, 
and the HttpContext only exists for received requests so an HttpContext would not exist for request (B).



**One possible workaround**:
You will have access to the headers when you make the dependent request.
At this time, you could manually track your Dependency:

```
var telemetryClient = new Microsoft.ApplicationInsights.TelemetryClient();
telemetryClient.TrackDependency();
```
			
However, this will create duplicate Dependency logs, that you will have to remediate.
You can either write a TelemetryProcessor and filter Dependency logs that do not include your headers.
Or, you could disable automatic Dependency collection by removing it from the config.
Note that this would disable ALL dependency collection, including for example SQL databases.




**Questions for Further discussion**:

2. What are you trying to accomplish by collecting these headers? 

We might be able to provide a different workaround if we better understand your goals.


3. How common do you think this would be for your project?
4. How common do you think this might be for other customers?

We could consider supporting this scenario in the future if it was a need by the community at large.
We don't automatically collect headers because they could contain PII or be very large which would impact customer billing.

**Comment by sanjaysingh** [comment] 2017-11-10 19:06
1. I am trying to include headers from request A to the dependency telemetry log. A different question, is there an easy to access headers of request B? The given workaround does not work for us. It requires code changes one and second it is going to have duplicate telemetries.

2.  There are two main motives. The first one is correlation. We have some existing distributed tracing implementation (loosely based onopentracing) based off http headers (4 headers) that we want to see with every telemetry that is emitted off of a request context. And second there are some additional contextual headers that is helpful if readily available with the telemetry. We can join the dependencies with the requests AppInsight table but that is not very clean either.

3. In my opinion it should be common for people who have done any kinds distributed tracing implementation or even just when they need to see some http header context side by side with the dependency telemetry being logged.

4. Same as 3 i guess.

All being side, we have found workaround that seems to be working fine for us. Please share your opinion if that is a good approach in the interim.

We wrote a custom HttpModule to extract the headers and write it to the current CallContext as follows:
```
CallContext.LogicalSetData("MyCustomHeader", HttpContext.Current.Request.Headers["X-MyCustomHeader"]);
```
Then in the custom telemetry initializer we populate custom dimension as follows:
```
telemetry.Context.Properties["MyCustomHeader"] = CallContext.LogicalGetData("MyCustomHeader").ToString();
```

CallContext state is not lost when dependency telemetry is called  and it is working fine for us from some testing that we have done till now.

Do you see any issues with going this route? Also if it is good to go then can it be made easier in the framework so that we don't have to do all this plumbing?

**Comment by MS-TimothyMothra** [comment] 2017-11-20 23:32
I'm going to close this issue and we will track the newer.

**Closed by MS-TimothyMothra** 2017-11-20 23:32 UTC
